name: Windows Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build GL-Cat
        run: |
          cd ./build
          cmake ..
          cmake --build . --config Release
